version: '3'

services:
  nginx_server:
    image: nginx
    ports:
      - 80:80
    volumes:
      - $PWD/nginx/:/etc/nginx/conf.d/
    depends_on:
      - jenkins_server
  jenkins_server:
    image: jenkinsci/blueocean
    container_name: jenkins_server
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
