pipeline{
    agent any
    stages{
        stage('init'){
        
        }
        stage('build'){
        
        }
        stage('ut'){
        
        }
        stage('security'){
        
        }
        stage('push'){
        
        }
    }
    post{
        success{
        
        }
    failure{
    
    }
    }
}
